### ISSUE TITLE
Swift compiler error "error: no such module 'PackageDescription' while attempting to build the showcase app for Android (as well as any other iOS app)

### ISSUE THREAD

**Issue by OmerFlame** [kodika/MutataApp#1]
I did exactly as I was told in the guide (except for the OpenJDK step, I had to install it using temurin8 because there is not available cask for Apple Silicon at the moment for... some reason).

The following link will give you the entire output of gradle.

[https://app.warp.dev/block/sHnXo1XK8YkjpNGq8w3wi5](https://app.warp.dev/block/sHnXo1XK8YkjpNGq8w3wi5)

Another issue that should raise your attention is the license updating script, it prints the following error:

[https://app.warp.dev/block/LZCfxRZPeR3rqp3LFHE0Gq](https://app.warp.dev/block/LZCfxRZPeR3rqp3LFHE0Gq)

I am pretty sure that this will cause issues down the line at **some** point.

Can you help me with the compilation issue? Your project looks really promising and I just want to see how it performs in the real world!

Thanks for igniting the possibility of cross-platform iOS apps!

**Comment by kostassite** [comment]
About the first issue:
Have you installed the Swift 5.4.2 Toolchain for Xcode?

- Download Official Swift 5.4.2 Toolchain for Xcode from https://swift.org/builds/swift-5.4.2-release/xcode/swift-5.4.2-RELEASE/swift-5.4.2-RELEASE-osx.pkg and install it.

About the license problem:
Please delete the `license.json` and rerun  the `./scripts/40-DownloadFreeLicense.sh your@email.com`

**Comment by OmerFlame** [comment]
Yes, I did! It gives me the same issues.

After seeing the constant failures, I decided to try to create a test Swift Package and try to compile it. Low and behold, it gives off the same issue.

I am suspecting that the Swift version that you require (more like swift-android requires) is only compatible with macOS Big Sur and not Monterey. Welp.

Maybe I am jumping to conclusions, I'd like to hear what you think!

**Comment by OmerFlame** [comment]
Also, I think it will be beneficial to clarify that I am using Xcode 13 (the system has a Swift version of 5.5.2, but I installed and switched to Swift 5.4.2 and when I try to compile anything, hell, even open a REPL, it gives me error everywhere).

**Comment by OmerFlame** [comment]
Never Mind. I fixed the issue with PackageDescription and stuff by installing Xcode 12 alongside Xcode 13 and switching to it in xcode-select. You should document this!

**Comment by kostassite** [comment]
Thanks for this. We are in the process of testing it with your setup to see exactly the problem, as there shouldn't be any problem with XCode 13. We will update the docs with the exact steps. Which Xcode 12 did you finally install?

**Comment by OmerFlame** [comment]
Xcode 12.5.1, since it contains an official distribution of Swift 5.4.2. Also, look at the new issue I found, I think it's really urgent.
