### ISSUE TITLE
Wondering whether I could utilize this with Github Actions, without having to use a Mac :)

### ISSUE THREAD

**Issue by aexarchos** [kodika/MutataApp#13]
Geia sou patrida :p hairomai panta otan ena endiaferon project pou vrisko tyxainei na einai apo ellina dev.

While setting up a h*tosh, using VMs or simply borrowing a mac would do the trick I actually had this idea of utilizing your project on the cloud through Github Actions, seeing whether I can configure everything beforehand and have the whole task run via scripts on github action, without user input.

I am just trying to quickly build/port an iOS app from a public repo to Android for fun, in hopes I can avoid having to sink my teeth into swift, having to get access to a mac or actually doing a full-fledged port xD

Never developed anything for iOS before, getting Android apps to build from public repos by writing a workflow, without even opening an IDE on a computer was easy peasy up to now, lol.

Therma hairetismata

**Comment by kostassite** [comment]
Hi,
Even though it would be possible to do it using Github actions, I am not sure about the cost as it would take lots of time in GitHub's machines. You can try it although :)
