### ISSUE TITLE
Swift compiler can't find CGFloat

### ISSUE THREAD

**Issue by OmerFlame** [kodika/MutataApp#4]
When I try to compile a simple app that uses a CGFloat explicitly, like this:

``let cgFloat = CGFloat(255)``

The compiler tells me that it doesn't know what a CGFloat is (yes, I imported UIKit).

But when a function takes a parameter of type CGFloat (a function that is defined outside of my program, e.g. inside UIKit) and I give it a parameter that is not a CGFloat, the compiler suddenly tells me that the function requests a CGFloat and not something else.

**Comment by kostassite** [comment]
Could you try  to
```Swift
import Foundation
import UIKit
```
at the top of your file?

**Comment by OmerFlame** [comment]
I am currently not at home so I can't try it, but maybe it will work. Also, when I try to compile my own small Mutata testing project, it compiles but when I try to open the app inside an Android emulator, it seems to open, leading you to a blank screen and then immediately crash(?) back to the home screen. Is there any special procedure to making an Xcode project that is Mutata-compliant, if that makes sense?

Also, are there any news about progress with Mutata?

**Comment by OmerFlame** [comment]
@kostassite it works! Though, now I am facing another issue: When I try to modify the sample app by adding my own view controller to the list of demo view controllers (all in the same fashion as the other view controllers) and I set all of the outlets and everything and then try to show the view controller itself, it just gives me a blank view controller, without any of the layout and components I put in the XIB file.

**Comment by kostassite** [comment]
When you add or change an image or a .xib, you need to rerun the [scripts/18-CopyIosImagesAndXibs.sh](https://github.com/kodika/MutataApp/tree/master/scripts/18-CopyIosImagesAndXibs.sh) or manually add the file in the `./copiedFromPackage/assets` folder

**Comment by OmerFlame** [comment]
I am just running scripts/100-UpdateAndRun, I believe that should have the exact same effect?

**Comment by kostassite** [comment]
Yeah. It should. If you do any change in the current VCs, do you see the difference? 

iOS and macOS take the files for different path

**Comment by OmerFlame** [comment]
I am running the app on macOS using Mac Catalyst and the paths don't matter at all.

**Comment by OmerFlame** [comment]
Well... now I am having issues turning the emulator on at the moment.

_sigh_

This will take bit.

**Comment by kostassite** [comment]
> I am running the app on macOS using Mac Catalyst and the paths don't matter at all.

I didn't mean between iOS and macOS. These are the same.
I mean that Mutata uses a copy of these files. You can see that the files do exist also in `./build/iOSFiles/copiedFromPackage/assets`

**Comment by OmerFlame** [comment]
Alright.

When I try to change an existing thing (the color of the top view in the Segmented Control demo), it changes in the Android app.

However, when I add a segmented control to the bottom of the view controller (without any container view, because it shouldn't require one), it doesn't show up at all.

**Comment by kostassite** [comment]
Could you add just a red UIView and set its constraints for top and left, and for width  and height. Or try set  the constraints for the Segmented. In Android, you always need to set the constraints as they are not autogenerated like in iOS.

**Comment by OmerFlame** [comment]
<img width="1333" alt="Screen Shot 2022-03-14 at 12 18 44" src="https://user-images.githubusercontent.com/17903236/158152681-9647320b-e891-4684-9dc3-283a529d3959.png">

Notice the segmented control at the bottom appearing in Mac Catalyst, but not appearing at all in the Android emulator (both have the latest XIB files).

**Comment by OmerFlame** [comment]
The segmented control already have its positioning constraints as well as leading and trailing constraints (top, leading and trailing)!

**Comment by OmerFlame** [comment]
Closing this issue.

I fixed it by actually manually setting a height constraint to the segmented control. Sorry for bugging you!
