### ISSUE TITLE
./scripts/15-ConvertIosProject.sh - line 27: 26093 Illegal instruction: 4

### ISSUE THREAD

**Issue by civocr** [kodika/MutataApp#6]
Hey guys

trying to convert an app I have for iOS to Android.

I use pods for ios and the only pods are MapBox's navigation sdk. 

Receiving this error but cant see anyway to get past it

./scripts/15-ConvertIosProject.sh: line 27: 26093 Illegal instruction: 4  $MUTATA_LIBS_PATH/swiftSelectorsRewriter --cleanObjc --IBActionSelectorsOutput IBActionsMutata.swift ./Sources

**Comment by kostassite** [comment]
Hi, this looks like it has nothing to do with MapBox. Were you able to run our MutataShowcase project successfully?

**Comment by civocr** [comment]
Just tried Showcase app. every step worked except for InstallAndRun



    > Task :app:installSwiftTools FAILED
    Installing Swift Build Tools v1.9.7-swift5.4
    env: python: No such file or directory
    
    > Task :app:kaptDebugKotlin
    warning: JavaSwiftProcessor init started
    warning: Package moduleName: MutataRunnerApp
    warning: JavaSwiftProcessor init finished successfully
    warning: The following options were not recognized by any processor: '[com.readdle.codegen.package, kapt.kotlin.generated]'
    
    FAILURE: Build failed with an exception.
    
    * What went wrong:
    Execution failed for task ':app:installSwiftTools'.
    > Process 'command '/Users/jason/Development/MutataApp/mutata_libs/swift-android-5.4-r1/bin/swift-android'' finished with non-zero exit value 127
    
    * Try:
    > Run with --stacktrace option to get the stack trace.
    > Run with --info or --debug option to get more log output.
    > Run with --scan to get full insights.
    
    * Get more help at https://help.gradle.org
    
    Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
    
    You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
    
    See https://docs.gradle.org/7.4.2/userguide/command_line_interface.html#sec:command_line_warnings
    
    BUILD FAILED in 3m 19s
    20 actionable tasks: 20 executed

**Comment by kostassite** [comment]
It looks like you are missing python.
What's the result of `python --version` command?

**Comment by civocr** [comment]
Python 3.10.3

**Comment by kostassite** [comment]
You will need to have python 2.7.x.

**Comment by neerajbaid** [comment]
I'm also running into this issue "Illegal instruction". Not sure what's causing it.

My only Cocoapod is `pod 'Alamofire', '~> 5.2'`

I have Python 2.7.18.

I'm able to get the demo app past the `ConvertIosProject.sh` script, until `InstallAndRun` where I run into this issue:  https://github.com/kodika/MutataApp/issues/9.

**Comment by kostassite** [comment]
Issue #9 is now fixed so you should be able to retry. Also, there is no need for old python 2.7 any more. It should work with python3 now.

**Comment by Starsky89** [comment]
I am having exactly the same error like the OP.
```
./scripts/15-ConvertIosProject.sh: line 27: 20618 Illegal instruction: 4  $MUTATA_LIBS_PATH/swiftSelectorsRewriter --cleanObjc --IBActionSelectorsOutput IBActionsMutata.swift --performSelectorOutput NSObject+Perform.swift ./Sources
```

Any solutions? Running on Mac OS Ventura 13.5.1, Intel chipset.

**Comment by stharajiv** [comment]
I have having the similar issue, can you help?  

`./scripts/15-ConvertIosProject.sh: line 27: 37516 Illegal instruction: 4  $MUTATA_LIBS_PATH/swiftSelectorsRewriter --cleanObjc --IBActionSelectorsOutput IBActionsMutata.swift --performSelectorOutput NSObject+Perform.swift ./Sources`
